CREATE TABLE IF NOT EXISTS domain (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO domain (id, name)
VALUES (1, 'real-estate')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO domain (id, name)
VALUES (2, 'law-regulation')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO domain (id, name)
VALUES (3, 'recruitment')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO domain (id, name)
VALUES (4, 'auction')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

SELECT setval(
    pg_get_serial_sequence('domain', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 0) FROM domain), 1),
    true
);
