-- mcp_server / mcp_tool 테이블 + monitoring-mcp + search_house_price 시드.
-- input_schema 는 mcp-server/scripts/export_tool_schema.py search_house_price 출력을 그대로 박음.
-- 도구 명세 변경 시 동일 스크립트 재실행 후 후속 마이그레이션(V3+)으로 input_schema 갱신.

CREATE TABLE IF NOT EXISTS mcp_server (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    endpoint TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS mcp_tool (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id BIGINT NOT NULL REFERENCES mcp_server(id),
    domain_id BIGINT NOT NULL REFERENCES domain(id),
    name VARCHAR(100) NOT NULL,
    description TEXT,
    input_schema JSONB,
    UNIQUE (server_id, name)
);

-- application.yml 의 spring.ai.mcp.client.sse.connections.python-mcp.url 이
-- 실제 연결 시 우선. 아래 endpoint 는 docker-compose 내부 호스트 fallback.
INSERT INTO mcp_server (id, name, description, endpoint)
VALUES (1, 'monitoring-mcp', 'Python MCP server (FastMCP, SSE transport)', 'http://mcp-server:8090')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    endpoint = EXCLUDED.endpoint;

INSERT INTO mcp_tool (id, server_id, domain_id, name, description, input_schema)
SELECT 1,
       (SELECT id FROM mcp_server WHERE name = 'monitoring-mcp'),
       (SELECT id FROM domain WHERE name = 'real-estate'),
       'search_house_price',
       '국토교통부 아파트 매매 실거래가 조회. region(시군구명 또는 LAWD_CD 5자리)과 deal_ymd(YYYYMM) 를 받아 통계 요약 + 가격 내림차순 상위 20건 trades 를 공통 스키마로 반환한다.',
       $JSON${
  "description": "search_house_price 입력.\n\nregion 은 자연어 시군구명(\"강남구\", \"서울 중구\", \"성남시 분당구\") 또는 5자리\n법정동코드(\"11680\") 모두 허용. 동·읍·면 단위는 지원하지 않는다.",
  "properties": {
    "region": {
      "description": "시군구명 또는 법정동코드 5자리. 예: '강남구', '서울 중구', '성남시 분당구', '11680'. 동음이의('중구', '동구' 등)는 시도와 함께 입력하세요(예: '서울 중구').",
      "title": "Region",
      "type": "string"
    },
    "deal_ymd": {
      "description": "거래 연월 YYYYMM. 예: '202403'.",
      "examples": [
        "202403"
      ],
      "pattern": "^[0-9]{6}$",
      "title": "Deal Ymd",
      "type": "string"
    }
  },
  "required": [
    "region",
    "deal_ymd"
  ],
  "title": "SearchHousePriceInput",
  "type": "object"
}$JSON$::jsonb
ON CONFLICT (id) DO UPDATE SET
    server_id = EXCLUDED.server_id,
    domain_id = EXCLUDED.domain_id,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    input_schema = EXCLUDED.input_schema;

SELECT setval(
    pg_get_serial_sequence('mcp_server', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 0) FROM mcp_server), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('mcp_tool', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 0) FROM mcp_tool), 1),
    true
);
